### ISSUE TITLE
Conductor NullPointerException in LogLastKmsg

### ISSUE THREAD

**Issue by shaseley** [phonelab/cm-shamu.manifest#12]
@gurupras: This happened after rebooting, and I encountered it twice in a row. Here's the stack trace:

`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver edu.buffalo.cse.phonelab.conductor.receivers.StartReceiver: java.lang.NullPointerException: Attempt to get length of null array`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2766)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at android.app.ActivityThread.-wrap14(ActivityThread.java)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:102)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:148)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:5461)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at edu.buffalo.cse.phonelab.conductor.receivers.StartReceiver$LogLastKmsg.logPstoreFiles(StartReceiver.java:54)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at edu.buffalo.cse.phonelab.conductor.receivers.StartReceiver$LogLastKmsg.run(StartReceiver.java:45)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at edu.buffalo.cse.phonelab.conductor.receivers.StartReceiver.onReceive(StartReceiver.java:26)`
`2016-08-21 22:04:42.073.73999995  3130  3130 E AndroidRuntime:  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2759)`

**Comment by shaseley** [comment]
After talking to @gurupras, it looks like this was caused by a custom boot.img I was using that did not have the necessary SELinux changes that allows the Conductor to read the `pstore` files. The API does indicate that the listFiles() can return null, so we should add a null check anyways.

**Comment by gurupras** [comment]
A fix for this has been pushed out to branch `last_kmsg_only` of the conductor. I will wait on @jhshi to merge it into develop

**Comment by jhshi** [comment]
Merged. Will push this out together with next OTA.

**Comment by jhshi** [comment]
Fixed in 4.1.8.
