### ISSUE TITLE
Missing Logging Infrastructure in Develop Branch

### ISSUE THREAD

**Issue by shaseley** [phonelab/cm-shamu.manifest#13]
`frameworks/base/core/java/edu/buffalo/cse/phonelab/json/` is missing in the develop branch. It looks like it may have been added individually to each of the logging branches. 

Can someone add this and make sure any other logging infrastructure is where it needs to be?

**Comment by jhshi** [comment]
@saintsantos: did you forgot to add the StrictJSONObject stuff to develop?

**Comment by saintsantos** [comment]
I thought I had it in there. I guess I merged it into logging, but not develop. I can add it in. 

⁣​

**Comment by jhshi** [comment]
Yeah, please do that and close this issue. Make sure you only merge the strictjsonobject, not the actual logging.

**Comment by saintsantos** [comment]
Added the Phonelab logging to the dev branch successfully
