### ISSUE TITLE
Disable CM's Update

### ISSUE THREAD

**Issue by jhshi** [phonelab/cm-shamu.manifest#2]
![2016-08-09 10 32 15](https://cloud.githubusercontent.com/assets/1173734/17526579/ad9b5662-5e1c-11e6-8925-f2200c9831d0.jpg)

**Comment by saintsantos** [comment]
Guru brought that up. though I already pulled out the cm updater, but I'm currently working on it nonetheless.

**Comment by jhshi** [comment]
Fixed in 4.0.5
