### ISSUE TITLE
Phone Does not Boot After OTA from 4.0.5 to 4.0.6

### ISSUE THREAD

**Issue by jhshi** [phonelab/cm-shamu.manifest#4]
OTAed from 4.0.5. Gets stuck at CM boot animation. Can not do `adb logcat` either (error message is : `read: unexpected length`.)

**Comment by jhshi** [comment]
Clean flash is OK. @saintsantos Can you flash 4.0.5 and let it OTA to 4.0.6 and see if the problem exists?

**Comment by jhshi** [comment]
Tried build a new platform (4.0.7) that only has phonelab/cm-13.0/develop branch. OTA from 4.0.5 to 4.0.7 does not work either. Same symptoms and same error message.

I suspect something is wrong in updating the boot image. Also, I did not see patch for /system/bin/kmsgd, which is supposed to be in the OTA package.

**Comment by saintsantos** [comment]
We added the patch yesterday. Pull device/moto/shamu and you should be good. Was also took Scott's device from 4.0.5 and adb sideloaded the ota and his device booted fine and there doesn't seem to be any issue.

**Comment by shaseley** [comment]
![screenshot_20160812-102919](https://cloud.githubusercontent.com/assets/2731352/17625762/331a714e-6078-11e6-95dc-7e7681524b8f.png)

**Comment by jhshi** [comment]
I did not see any new changes in device/moto/shamu. The last commit was from ef1dc at 8/11 1 pm.

**Comment by jhshi** [comment]
OTA 4.0.7 -> 4.0.8 works.

**Comment by jhshi** [comment]
Fixed by setting SELinux to permissive mode in recovery kernel.
