### ISSUE TITLE
Use tracetime in the Conductor

### ISSUE THREAD

**Issue by shaseley** [phonelab/cm-shamu.manifest#6]
Now that the `tracetime` format has been added to `logcat`, can we make this the default format?

**Comment by jhshi** [comment]
Does it require the conductor changes from Guru?

**Comment by shaseley** [comment]
Not for this part. Eventually, when we incorporate the rest of the tracing infrastructure, we'll need to worry about Guru's conductor changes. For now, our thought was to use the new tracetime format as the new default for all logging going forward so we get boot_id and log line token. For this change, it should be as simple as changing the format from threadtime -> tracetime in the manifest/conductor.

**Comment by jhshi** [comment]
Got it. Enabled in manifest.
