### ISSUE TITLE
Low Headphone Volume

### ISSUE THREAD

**Issue by shaseley** [phonelab/cm-shamu.manifest#8]
The max headphone volume of the Nexus 6 is too low, which is very noticeable when connecting the device to external speakers, e.g. car stereo. This can be fixed by changing the RX1 and RX2 digital volume settings in device/moto/shamu/mixer_paths.xml.

Jinghao - I've fixed this and tested it in my car and the new volume levels are reasonable. Can I go ahead and push this?

**Comment by jhshi** [comment]
Sure, go ahead. Will be pushed in next OTA.

**Comment by jhshi** [comment]
Actually let me close this when the new OTA is pushed.

**Comment by jhshi** [comment]
Fixed in 4.1.4
